# Основной конфиг плагина OriginChat
version: 1

# Общие настройки плагина
settings:
  # Включить/выключить отладочные сообщения
  debug: false
  # Префикс плагина в сообщениях
  prefix: '&7[&bOriginChat&7]'

# Настройки форматирования чата

# Настройки модулей
modules:
  # Включенные модули
  enabled:
    - 'chat'
    - 'tab'
    - 'private_messages'
    - 'roleplay'
    - 'server_messages'
    - 'locale_advancements'
    - 'locale_deaths'