name: OriginChat
version: '0.2.0-alpha.1'
main: me.nagibatirowanie.originchat.OriginChat
api-version: '1.17'
authors: [ nagibatirowanie ]
description: 'Продвинутый плагин для форматирования чата'

# Зависимости плагина
depend: [ ProtocolLib ]
softdepend: [PlaceholderAPI]

# Команды плагина
commands:
  originchat:
    description: Основная команда плагина OriginChat
    aliases: [ochat, oc]
    usage: /originchat <reload|module|animation|help>
    permission: originchat.admin
  msg:
    description: Отправить приватное сообщение игроку
    aliases: [tell, w, whisper]
    usage: /msg <игрок> <сообщение>
    permission: originchat.pm.send
  r:
    description: Ответить на последнее полученное приватное сообщение
    aliases: [reply]
    usage: /r <сообщение>
    permission: originchat.pm.reply
  clearchat:
    description: Очистить чат для всех игроков
    aliases: [cc]
    usage: /clearchat
    permission: originchat.command.clearchat
  # Команды ролевой игры
  me:
    description: Действие от первого лица
    usage: /me <действие>
    permission: originchat.roleplay.me
  gme:
    description: Глобальное действие от первого лица
    usage: /gme <действие>
    permission: originchat.roleplay.gme
  do:
    description: Описание окружения
    usage: /do <описание>
    permission: originchat.roleplay.do
  gdo:
    description: Глобальное описание окружения
    usage: /gdo <описание>
    permission: originchat.roleplay.gdo
  try:
    description: Попытка действия с случайным результатом
    usage: /try <действие>
    permission: originchat.roleplay.try
  gtry:
    description: Глобальная попытка действия с случайным результатом
    usage: /gtry <действие>
    permission: originchat.roleplay.gtry
  todo:
    description: Действие с описанием
    usage: /todo <действие>
    permission: originchat.roleplay.todo
  gtodo:
    description: Глобальное действие с описанием
    usage: /gtodo <действие>
    permission: originchat.roleplay.gtodo
  roll:
    description: Бросок кубика
    usage: /roll <мин> <макс>
    permission: originchat.roleplay.roll
  groll:
    description: Глобальный бросок кубика
    usage: /groll <мин> <макс>
    permission: originchat.roleplay.groll
  ball:
    description: Магический шар
    usage: /ball <вопрос>
    permission: originchat.roleplay.ball
  gball:
    description: Глобальный магический шар
    usage: /gball <вопрос>
    permission: originchat.roleplay.gball
  translatetoggle:
    description: Включить/выключить автоматический перевод сообщений
    aliases: [ttoggle]
    usage: /translatetoggle [on|off]
    permission: originchat.translate
  dbinfo:
    description: Информация о базе данных
    usage: /dbinfo [player <имя>|stats]
    permission: originchat.admin
  afk:
    description: Toggle AFK status
    usage: /afk

# Права плагина
permissions:
  originchat.admin:
    description: Доступ к административным командам плагина
    default: op
  originchat.command.clearchat:
    description: Доступ к команде очистки чата
    default: op
  originchat.animation:
    description: Базовый доступ к командам анимаций
    default: true
  originchat.animation.reload:
    description: Доступ к перезагрузке анимаций
    default: op
  originchat.animation.list:
    description: Доступ к просмотру списка анимаций
    default: true
  originchat.animation.info:
    description: Доступ к просмотру информации об анимациях
    default: true
  originchat.animation.preview:
    description: Доступ к предпросмотру анимаций
    default: true
  originchat.module.chat:
    description: Доступ к функциям модуля чата
    default: true
  originchat.module.servermessages:
    description: Доступ к функциям модуля серверных сообщений
    default: true
  originchat.pm.send:
    description: Доступ к отправке приватных сообщений
    default: true
  originchat.pm.reply:
    description: Доступ к ответу на приватные сообщения
    default: true
  originchat.afk:
    description: Доступ к команде AFK
    default: true
  # Права для ролевых команд
  originchat.roleplay.me:
    description: Доступ к команде /me
    default: true
  originchat.roleplay.gme:
    description: Доступ к команде /gme
    default: true
  originchat.roleplay.do:
    description: Доступ к команде /do
    default: true
  originchat.roleplay.gdo:
    description: Доступ к команде /gdo
    default: true
  originchat.roleplay.try:
    description: Доступ к команде /try
    default: true
  originchat.roleplay.gtry:
    description: Доступ к команде /gtry
    default: true
  originchat.roleplay.todo:
    description: Доступ к команде /todo
    default: true
  originchat.roleplay.gtodo:
    description: Доступ к команде /gtodo
    default: true
  originchat.roleplay.roll:
    description: Доступ к команде /roll
    default: true
  originchat.roleplay.groll:
    description: Доступ к команде /groll
    default: true
  originchat.roleplay.ball:
    description: Доступ к команде /ball
    default: true
  originchat.roleplay.gball:
    description: Доступ к команде /gball
    default: true
  originchat.translate:
    description: Доступ к управлению автоматическим переводом сообщений
    default: true
  originchat.chat.formatting:
    description: Доступ к использованию цветов и hex/minimessage форматирования в чате
    default: op
  originchat.chat.placeholders:
    description: Доступ к использованию плейсхолдеров и анимаций в чате
    default: op
  # Права для кулдауна чата
  originchat.chat.cooldown.0:
    description: Отключение кулдауна чата
    default: op
  originchat.chat.cooldown.3:
    description: Установка кулдауна чата в 3 секунды
    default: false
  originchat.chat.cooldown.10:
    description: Установка кулдауна чата в 10 секунд
    default: false
