# Main configuration file for the OriginChat plugin
config-version: 3

# General plugin settings
settings:
  # Enable/disable debug messages
  debug: false
  # Plugin prefix in messages
  prefix: '&7[&bOriginChat&7]'

# Locale settings
locale:
  # Default language (ru, en)
  default: 'en'
  # Enable automatic language detection from client
  auto_detect: true

# Chat formatting settings

# Module settings
modules:
  # Enabled modules
  enabled:
    - 'chat'
    - 'tab'
    - 'private_messages'
    - 'roleplay'
    - 'server_messages'
    - 'locale_advancements'
    - 'locale_deaths'
    - 'scoreboard'
    - 'server_brand'
    - 'mentions'
    - 'player_info'
    - 'emoji'
